#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("BarBot.Droid.Resource", IsApplication=true)]

namespace BarBot.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::BarBot.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int fontPath = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070002
			public const int actionbar_gray = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int background_gray = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int barbot_blue = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int text_white = 2131165187;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080003
			public const int action_bar_height = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int activity_horizontal_margin = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int activity_vertical_margin = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int navigation_drawer_width = 2131230722;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionbar_icon_placeholder_compat = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int actionbar_shadow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int CustomTile = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int HexagonTile = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int HexagonTileGradient = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_ab_up_compat = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int search = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int actionbar_textview = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int calligraphy_tag_id = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int container = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int gridview = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int menu_search = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int user_name = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int actionbar = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int DrinkDetail = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int DrinkMenu = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int NameDialogFragment = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int top_menus = 2131361792;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int drink_menu_title = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int hint_name_alert = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int submit_name_alert = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int title_name_alert = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int BarBotTheme = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int BarBotTheme_ActionBar = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int BarBotTheme_ActionBar_Title = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int BarBotTheme_GridView = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int OrderButton = 2131296260;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
